# Generated by Django 6.1.1 on 2026-09-16 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/')),
                ('link', models.CharField(blank=True, help_text='URL interna, ex.: /produtos?promocao=1', max_length=255)),
                ('cta', models.CharField(blank=True, max_length=40, verbose_name='texto do botão')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor fixo (R$)')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='promocoes', to='catalogo.categoria')),
                ('produtos', models.ManyToManyField(blank=True, related_name='promocoes', to='catalogo.produto')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
