# Generated by Django 6.1.1 on 2026-09-16 19:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_separacao', 'Em separação'), ('faturado', 'Faturado'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=15)),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto bancário'), ('pix', 'PIX'), ('carteira', 'Carnê / carteira'), ('deposito', 'Depósito antecipado')], max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('endereco_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entregues', to='clientes.endereco')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço un. congelado')),
                ('preco_caixa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço caixa congelado')),
                ('preco_efetivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço efetivo un.')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalogo.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'produto'), name='item_unico_por_pedido')],
            },
        ),
    ]
