# Generated by Django 6.1.1 on 2026-09-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Laboratórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone usado no frontend', max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('principio_ativo', models.CharField(max_length=200, verbose_name='princípio ativo')),
                ('tipo', models.CharField(choices=[('generico', 'Genérico'), ('similar', 'Similar'), ('referencia', 'Referência')], max_length=12)),
                ('prescricao', models.CharField(choices=[('livre', 'Livre'), ('com_prescricao', 'Com prescrição'), ('controlado', 'Controlado')], default='livre', max_length=15)),
                ('ean', models.CharField(blank=True, max_length=14, verbose_name='EAN/GTIN')),
                ('qtd_por_caixa', models.PositiveIntegerField(default=1, verbose_name='unidades por caixa')),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por unidade')),
                ('preco_caixa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por caixa')),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.laboratorio')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=40, verbose_name='número do lote')),
                ('quantidade', models.PositiveIntegerField()),
                ('validade', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Lote em estoque',
                'verbose_name_plural': 'Lotes em estoque',
                'ordering': ['validade'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaixaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.PositiveIntegerField()),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_caixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='catalogo.produto')),
            ],
            options={
                'ordering': ['quantidade_minima'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='catalogo_pr_slug_8b084e_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo'], name='catalogo_pr_ativo_88fb8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.UniqueConstraint(fields=('produto', 'numero_lote'), name='lote_unico_por_produto'),
        ),
        migrations.AddConstraint(
            model_name='faixapreco',
            constraint=models.UniqueConstraint(fields=('produto', 'quantidade_minima'), name='faixa_unica_por_qtd'),
        ),
    ]
